/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;

/**
 *
 * @author 54265
 */
public class JFSolBus extends javax.swing.JFrame {

    /**
     * Creates new form SolBus
     */
    public JFSolBus() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icono = new ImageIcon(getClass().getResource("/Vistas/bus.jpg"));
        Image miImagen = icono.getImage();
        jDesktopPane1 = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(miImagen,0,0,getWidth(),getHeight(),this);
            }
        };
        jMenuBar1 = new javax.swing.JMenuBar();
        jMPasajes = new javax.swing.JMenu();
        jMPasajeros = new javax.swing.JMenu();
        jMRutasHorarios = new javax.swing.JMenu();
        jMGuardarColectivo = new javax.swing.JMenu();
        jmiDisponibles = new javax.swing.JMenuItem();
        jMICrearCole = new javax.swing.JMenuItem();
        jMIBuscarCole = new javax.swing.JMenuItem();
        jMSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1241, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 843, Short.MAX_VALUE)
        );

        jMPasajes.setText("Pasajes");
        jMPasajes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMPasajesMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMPasajes);

        jMPasajeros.setText("Pasajeros");
        jMPasajeros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMPasajerosMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMPasajeros);

        jMRutasHorarios.setText("Rutas y Horarios");
        jMRutasHorarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMRutasHorariosMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMRutasHorarios);

        jMGuardarColectivo.setText("Colectivos");

        jmiDisponibles.setText("Ver Disponibles");
        jmiDisponibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiDisponiblesActionPerformed(evt);
            }
        });
        jMGuardarColectivo.add(jmiDisponibles);

        jMICrearCole.setText("Crear Colectivo");
        jMICrearCole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMICrearColeActionPerformed(evt);
            }
        });
        jMGuardarColectivo.add(jMICrearCole);

        jMIBuscarCole.setText("Buscar Colectivo");
        jMIBuscarCole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIBuscarColeActionPerformed(evt);
            }
        });
        jMGuardarColectivo.add(jMIBuscarCole);

        jMenuBar1.add(jMGuardarColectivo);

        jMSalir.setText("Salir");
        jMSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMSalirMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMSalirMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMSalirMouseClicked


    private void jMPasajesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMPasajesMouseClicked
        // TODO add your handling code here:
        JIFPasajes pasajes = new JIFPasajes();
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        
        int x = (jDesktopPane1.getWidth()/2) - (pasajes.getWidth()/2);
        int y = (jDesktopPane1.getHeight()/2) - (pasajes.getHeight()/2);
        pasajes.setLocation(x, y);
        
        pasajes.setVisible(true);
        jDesktopPane1.add(pasajes);
        jDesktopPane1.moveToFront(pasajes);
    }//GEN-LAST:event_jMPasajesMouseClicked

    private void jMICrearColeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMICrearColeActionPerformed
        // TODO add your handling code here:
         JIFCrearColectivo menuCrearCole= new JIFCrearColectivo();
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        menuCrearCole.setVisible(true);
        jDesktopPane1.add(menuCrearCole);
        jDesktopPane1.moveToFront(menuCrearCole);

    }//GEN-LAST:event_jMICrearColeActionPerformed

    private void jMIBuscarColeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIBuscarColeActionPerformed
        // TODO add your handling code here:
        JIFBuscarColectivo menuBuscarCole= new JIFBuscarColectivo();
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        menuBuscarCole.setVisible(true);
        jDesktopPane1.add(menuBuscarCole);
        jDesktopPane1.moveToFront(menuBuscarCole);
    }//GEN-LAST:event_jMIBuscarColeActionPerformed

    private void jmiDisponiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiDisponiblesActionPerformed
        // TODO add your handling code here:
        JIFColectivosDisponibles diponibles = new JIFColectivosDisponibles();
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        
       
        
        diponibles.setVisible(true);
        jDesktopPane1.add(diponibles);
        jDesktopPane1.moveToFront(diponibles);
    }//GEN-LAST:event_jmiDisponiblesActionPerformed

    private void jMRutasHorariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMRutasHorariosMouseClicked
        // TODO add your handling code here:
        GestionRutas rutas = new GestionRutas();
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();        
        rutas.setVisible(true);
        jDesktopPane1.add(rutas);
        jDesktopPane1.moveToFront(rutas);
    }//GEN-LAST:event_jMRutasHorariosMouseClicked


    private void jMPasajerosMouseClicked(java.awt.event.MouseEvent evt) {                                         
        // TODO add your handling code here:
        JIFPasajero pasajero = new JIFPasajero();
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
         pasajero.setVisible(true);
        jDesktopPane1.add(pasajero);
        jDesktopPane1.moveToFront(pasajero);
    }
    
    private void jMIRutasActionPerformed(java.awt.event.ActionEvent evt) {                                         
        GestionRutas rutas = new GestionRutas();
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();        
        rutas.setVisible(true);
        jDesktopPane1.add(rutas);
        jDesktopPane1.moveToFront(rutas);
    }    
       
        

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMGuardarColectivo;
    private javax.swing.JMenuItem jMIBuscarCole;
    private javax.swing.JMenuItem jMICrearCole;
    private javax.swing.JMenu jMPasajeros;
    private javax.swing.JMenu jMPasajes;
    private javax.swing.JMenu jMRutasHorarios;
    private javax.swing.JMenu jMSalir;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmiDisponibles;
    // End of variables declaration//GEN-END:variables
}
